name: Rename Template to Plugin Name

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Remove this workflow file
        run: |
          NAME="${{ github.event.repository.name }}"
          rm .github/workflows/template-init.yml
          # Replace HytalePluginTemplate in settings.gradle
          sed -i "s/HytalePluginTemplate/$NAME/g" settings.gradle
          # Replace HytalePluginTemplate in HytalePluginTemplate.java
          sed -i "s/HytalePluginTemplate/$NAME/g" src/main/java/io/profidev/HytalePluginTemplate/HytalePluginTemplate.java
          mkdir -p src/main/java/io/profidev/$NAME
          mv src/main/java/io/profidev/HytalePluginTemplate/HytalePluginTemplate.java src/main/java/io/profidev/$NAME/$NAME.java

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Renamed template to plugin name"
          branch: refactor/rename-to-plugin-name
          title: "Rename template to plugin name"
          body: "This PR renames the template to the plugin name."
          base: main
          sign-commits: true
